# Generated by Django 2.0.5 on 2018-07-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=70, unique=True)),
                ('college', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=10)),
            ],
        ),
    ]
