# Generated by Django 2.0.5 on 2018-07-22 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_no',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
